# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d17be78974105d90afba1dbf7f5555127d71173cc1c08571bb7d0c40657fd9d31df55312c13349b757e3ebbce3723c74024230756bd1f1a881bc8d3935c47272

test:
  secret_key_base: efb81f4bfe4c38e39727e37ba2083b4fb0da160e84ff7911675816d844df1611edf9cf5b98d386e5f99e748f85eceaaa2fce54edc8e0d39f3ce1378648399799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
